import BarcodeGenerator from "./barcode-generator"
import FrequencySpectrumGenerator from "./frequency-spectrum-generator"
import NoiseFieldGenerator from "./noise-field-generator"
import PixelatedNoiseGenerator from "./pixelated-noise-generator"
import BrownianMotionGenerator from "./brownian-motion-generator"
import TrigonometricCircleGenerator from "./trigonometric-circle-generator"
import type { PatternGenerator } from "./types"

export const patternGenerators: PatternGenerator[] = [
  {
    id: "barcode",
    name: "Barcode Scanner",
    component: BarcodeGenerator,
    controls: [
      {
        id: "scrollSpeed",
        label: "Scroll Speed",
        type: "range",
        min: 0.5,
        max: 8.0,
        step: 0.5,
        defaultValue: 2,
      },
      {
        id: "barDensity",  
        label: "Bar Density",
        type: "range",
        min: 0.2,
        max: 0.9,
        step: 0.1,
        defaultValue: 0.6,
      },
      {
        id: "scannerSpeed",
        label: "Scanner Speed", 
        type: "range",
        min: 0.5,
        max: 5.0,
        step: 0.5,
        defaultValue: 2,
      },
      {
        id: "scannerOpacity",
        label: "Scanner Opacity",
        type: "range", 
        min: 0.1,
        max: 1.0,
        step: 0.1,
        defaultValue: 0.6,
      },
      {
        id: "colorScheme",
        label: "Color Scheme",
        type: "select",
        defaultValue: "classic",
        options: [
          { value: "classic", label: "CLASSIC" },
          { value: "inverted", label: "INVERTED" },
          { value: "blue", label: "BLUE_TONE" },
          { value: "green", label: "GREEN_TONE" },
          { value: "amber", label: "AMBER_TONE" },
        ],
      },
      {
        id: "showScanner",
        label: "Show Scanner",
        type: "checkbox",
        defaultValue: true,
      },
    ],
  },
  {
    id: "frequency",
    name: "Frequency Spectrum",
    component: FrequencySpectrumGenerator,
    controls: [
      {
        id: "barWidth",
        label: "Bar Width",
        type: "range",
        min: 1,
        max: 8,
        step: 1,
        defaultValue: 3,
      },
      {
        id: "updateSpeed",
        label: "Update Speed",
        type: "range",
        min: 10,
        max: 200,
        step: 10,
        defaultValue: 50,
      },
      {
        id: "intensity",
        label: "Intensity",
        type: "range",
        min: 0.2,
        max: 2.0,
        step: 0.1,
        defaultValue: 1.0,
      },
      {
        id: "bassBoost",
        label: "Bass Boost",
        type: "range",
        min: 0.1,
        max: 1.0,
        step: 0.1,
        defaultValue: 0.7,
      },
      {
        id: "colorScheme",
        label: "Color Scheme",
        type: "select",
        defaultValue: "green",
        options: [
          { value: "green", label: "GREEN_SPECTRUM" },
          { value: "blue", label: "BLUE_SPECTRUM" },
          { value: "purple", label: "PURPLE_SPECTRUM" },
          { value: "rainbow", label: "RAINBOW_SPECTRUM" },
          { value: "amber", label: "AMBER_SPECTRUM" },
        ],
      },
      {
        id: "glow",
        label: "Glow Effects",
        type: "checkbox",
        defaultValue: true,
      },
    ],
  },
  {
    id: "noise",
    name: "Noise Field",
    component: NoiseFieldGenerator,
    controls: [
      {
        id: "noiseScale",
        label: "Noise Scale",
        type: "range",
        min: 0.005,
        max: 0.1,
        step: 0.005,
        defaultValue: 0.02,
      },
      {
        id: "animationSpeed",
        label: "Animation Speed",
        type: "range",
        min: 0.001,
        max: 0.05,
        step: 0.001,
        defaultValue: 0.01,
      },
      {
        id: "contrast",
        label: "Contrast",
        type: "range",
        min: 0.5,
        max: 3.0,
        step: 0.1,
        defaultValue: 1.0,
      },
      {
        id: "brightness",
        label: "Brightness",
        type: "range",
        min: 0.5,
        max: 2.0,
        step: 0.1,
        defaultValue: 1.0,
      },
      {
        id: "colorMode",
        label: "Color Mode",
        type: "select",
        defaultValue: "blue",
        options: [
          { value: "blue", label: "BLUE_FIELD" },
          { value: "plasma", label: "PLASMA_FIELD" },
          { value: "fire", label: "FIRE_FIELD" },
          { value: "ice", label: "ICE_FIELD" },
          { value: "electric", label: "ELECTRIC_FIELD" },
        ],
      },
    ],
  },
  {
    id: "pixelated-noise",
    name: "Pixelated Noise",
    component: PixelatedNoiseGenerator,
    controls: [
      {
        id: "pixelSize",
        label: "Pixel Size",
        type: "range",
        min: 2,
        max: 32,
        step: 1,
        defaultValue: 8,
      },
      {
        id: "noiseScale",
        label: "Noise Scale",
        type: "range",
        min: 0.01,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.1,
      },
      {
        id: "animationSpeed",
        label: "Animation Speed",
        type: "range",
        min: 0.001,
        max: 0.1,
        step: 0.001,
        defaultValue: 0.02,
      },
      {
        id: "colorIntensity",
        label: "Color Intensity",
        type: "range",
        min: 0.1,
        max: 2.0,
        step: 0.1,
        defaultValue: 1.0,
      },
      {
        id: "colorScheme",
        label: "Color Scheme",
        type: "select",
        defaultValue: "retro",
        options: [
          { value: "retro", label: "RETRO_PALETTE" },
          { value: "monochrome", label: "MONOCHROME" },
          { value: "cyan", label: "CYAN_MATRIX" },
          { value: "amber", label: "AMBER_TERMINAL" },
        ],
      },
    ],
  },
  {
    id: "brownian-motion",
    name: "Brownian Motion",
    component: BrownianMotionGenerator,
    controls: [
      {
        id: "particleCount",
        label: "Particle Count",
        type: "range",
        min: 1,
        max: 20,
        step: 1,
        defaultValue: 12,
      },
      {
        id: "speed",
        label: "Speed",
        type: "range",
        min: 0.1,
        max: 3.0,
        step: 0.1,
        defaultValue: 1.0,
      },
      {
        id: "brightness",
        label: "Brightness",
        type: "range",
        min: 0.5,
        max: 5.0,
        step: 0.1,
        defaultValue: 2.0,
      },
      {
        id: "trailLength",
        label: "Trail Length",
        type: "range",
        min: 2,
        max: 15,
        step: 1,
        defaultValue: 8,
      },
      {
        id: "jitterAmount",
        label: "Brownian Jitter",
        type: "range",
        min: 0.01,
        max: 0.2,
        step: 0.01,
        defaultValue: 0.05,
      },
    ],
  },
  {
    id: "trigonometric-circle",
    name: "Trigonometric Circle",
    component: TrigonometricCircleGenerator,
    controls: [
      {
        id: "speed",
        label: "Animation Speed",
        type: "range",
        min: 0.1,
        max: 3.0,
        step: 0.1,
        defaultValue: 1.0,
      },
    ],
  },
]

export { BarcodeGenerator, FrequencySpectrumGenerator, NoiseFieldGenerator, PixelatedNoiseGenerator, BrownianMotionGenerator, TrigonometricCircleGenerator }
export type { PatternGenerator, PatternGeneratorProps } from "./types"
