# AIDEV-NOTE: Weekly security scanning workflow for automated vulnerability detection
name: Security Scan

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/security.yml'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Run npm audit fix (dry run)
      run: npm audit fix --dry-run
      continue-on-error: true
      
    - name: Check for outdated packages
      run: npm outdated
      continue-on-error: true
      
    - name: Create security report
      if: failure()
      run: |
        echo "## Security Scan Results" > security-report.md
        echo "Date: $(date)" >> security-report.md
        echo "" >> security-report.md
        echo "### Vulnerabilities Found:" >> security-report.md
        npm audit --audit-level=moderate --json >> security-report.md 2>/dev/null || echo "Audit failed" >> security-report.md
        
    - name: Upload security report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: security-report.md
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "🚨 Security vulnerabilities detected!"
        echo "Please review the security report artifact."
        echo "Consider running: npm audit fix"